[2025-03-05T05:57:26.061+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T05:57:26.095+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load_data_to_elastic_search_rag.loads_csv_data scheduled__2025-03-04T00:00:00+00:00 [queued]>
[2025-03-05T05:57:26.120+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load_data_to_elastic_search_rag.loads_csv_data scheduled__2025-03-04T00:00:00+00:00 [queued]>
[2025-03-05T05:57:26.122+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-05T05:57:26.147+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): loads_csv_data> on 2025-03-04 00:00:00+00:00
[2025-03-05T05:57:26.176+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Load_data_to_elastic_search_rag', 'loads_csv_data', 'scheduled__2025-03-04T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp2pd3n9dj']
[2025-03-05T05:57:26.180+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask loads_csv_data
[2025-03-05T05:57:26.181+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1361) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-05T05:57:26.183+0000] {standard_task_runner.py:72} INFO - Started process 1363 to run task
[2025-03-05T05:57:26.331+0000] {task_command.py:467} INFO - Running <TaskInstance: Load_data_to_elastic_search_rag.loads_csv_data scheduled__2025-03-04T00:00:00+00:00 [running]> on host a6ec32231613
[2025-03-05T05:57:26.583+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Artur Tiburski' AIRFLOW_CTX_DAG_ID='Load_data_to_elastic_search_rag' AIRFLOW_CTX_TASK_ID='loads_csv_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-04T00:00:00+00:00'
[2025-03-05T05:57:26.585+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-05T05:57:26.842+0000] {logging_mixin.py:190} INFO - Dados Inseridos com Sucesso.
[2025-03-05T05:57:26.844+0000] {python.py:240} INFO - Done. Returned value was: Data from CSV inserted succesfully
[2025-03-05T05:57:26.907+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-05T05:57:26.908+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Load_data_to_elastic_search_rag, task_id=loads_csv_data, run_id=scheduled__2025-03-04T00:00:00+00:00, execution_date=20250304T000000, start_date=20250305T055726, end_date=20250305T055726
[2025-03-05T05:57:26.963+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-05T05:57:27.010+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-05T05:57:27.023+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
