[2025-03-04T16:11:50.897+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T16:11:50.929+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load_data_to_elastic_search_rag.loads_csv_data manual__2025-03-04T16:11:37.441589+00:00 [queued]>
[2025-03-04T16:11:50.947+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load_data_to_elastic_search_rag.loads_csv_data manual__2025-03-04T16:11:37.441589+00:00 [queued]>
[2025-03-04T16:11:50.950+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-04T16:11:50.987+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): loads_csv_data> on 2025-03-04 16:11:37.441589+00:00
[2025-03-04T16:11:51.006+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Load_data_to_elastic_search_rag', 'loads_csv_data', 'manual__2025-03-04T16:11:37.441589+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpquwbx45l']
[2025-03-04T16:11:51.010+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask loads_csv_data
[2025-03-04T16:11:51.012+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=213) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-04T16:11:51.021+0000] {standard_task_runner.py:72} INFO - Started process 215 to run task
[2025-03-04T16:11:51.091+0000] {task_command.py:467} INFO - Running <TaskInstance: Load_data_to_elastic_search_rag.loads_csv_data manual__2025-03-04T16:11:37.441589+00:00 [running]> on host a6ec32231613
[2025-03-04T16:11:51.221+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Artur Tiburski' AIRFLOW_CTX_DAG_ID='Load_data_to_elastic_search_rag' AIRFLOW_CTX_TASK_ID='loads_csv_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-04T16:11:37.441589+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-04T16:11:37.441589+00:00'
[2025-03-04T16:11:51.224+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-04T16:11:51.281+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/airflow_module/dags/data_modules/data_load.py", line 80, in insert_csv_data
    "treatments": str(row['Treatments'].replace("'", "").replace('"', "").strip())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'replace'
[2025-03-04T16:11:51.309+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Load_data_to_elastic_search_rag, task_id=loads_csv_data, run_id=manual__2025-03-04T16:11:37.441589+00:00, execution_date=20250304T161137, start_date=20250304T161150, end_date=20250304T161151
[2025-03-04T16:11:51.336+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-04T16:11:51.339+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task loads_csv_data ('float' object has no attribute 'replace'; 215)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/airflow_module/dags/data_modules/data_load.py", line 80, in insert_csv_data
    "treatments": str(row['Treatments'].replace("'", "").replace('"', "").strip())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'replace'
[2025-03-04T16:11:51.401+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-04T16:11:51.444+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-04T16:11:51.447+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
